language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
  - pip install coverage
# add services
services: postgresql
# setup database
before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'andela21';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO tester;" -U postgres
# command to run tests
script: nosetests  --with-coverage --cover-package=ridemyway && coveralls

after_success: coveralls
# env vars
env:
    - FLASK_APP=run.py
    - FLASK_ENV=testing
    - TEST_DATABASE_NAME=testdb
    - DATABASE_HOST=localhost
    - DATABASE_USERNAME=tester
    - DATABASE_PASSWORD=andela21
