language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
  - pip install coverage
# add services
services: postgresql
# env vars
env:
  global:
    - FLASK_APP=run.py
    - FLASK_ENV=testing
    - TEST_DATABASE_NAME=travis_ci_test
    - DATABASE_HOST=localhost
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=travis

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create user postgres with password 'travis';' -U postgres
  - psql -c 'grant all privileges on database travis_ci_test to postgres;' -U postgres

# command to run tests
script: nosetests  --with-coverage --cover-package=ridemyway && coveralls

after_success: coveralls
