language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
  - pip install coverage
# add services
services: postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER yml WITH PASSWORD 'travis';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE travis_ci_test TO yml;" -U postgres
# env vars
env:
- FLASK_APP=run.py
- FLASK_ENV=testing
- TEST_DATABASE_NAME=travis_ci_test
- DATABASE_HOST=localhost
- DATABASE_USERNAME=travis
- DATABASE_PASSWORD=travis
# command to run tests
script: nosetests  --with-coverage --cover-package=ridemyway && coveralls

after_success: coveralls
