language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
  - pip install coverage

# command to run tests
script: nosetests  --with-coverage --cover-package=ridemyway && coveralls

after_success: coveralls
